"""inicial

Revision ID: 19f317b3c840
Revises: 
Create Date: 2024-11-21 13:40:26.554741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f317b3c840'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('instituicao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_autor')
    )
    op.create_table('capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('pagina_inicial', sa.Integer(), nullable=True),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['autores.id_autor'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capitulos')
    op.drop_table('autores')
    # ### end Alembic commands ###
